class Cl_AssertSame:Cl_Assertion{
    Object Val1,
           Val2;

    static
    Cl_Assertion Create(Object Val1, Object Val2){
        Cl_AssertSame Result=new('Cl_AssertSame');
        Result.Val1=Val1;
        Result.Val2=Val2;
        Result.ErrorMsg="Values were not the same";
        return Result;
    }

    override
    bool Eval()
    {return Val1==Val2;}
}

extend
class Clematis{
    Cl_Assertion AssertSame(Object Val1, Object Val2)
    {return Cl_AssertSame.Create(Val1, Val2);}
}