class Cl_AssertTrue:Cl_Assertion{
    bool Condition;

    static
    Cl_Assertion Create(bool Condition){
        Cl_AssertTrue Result=new('Cl_AssertTrue');
        Result.Condition=Condition;
        Result.ErrorMsg="Value was not true";
        return Result;
    }

    override
    bool Eval()
    {return Condition;}
}

extend
class Clematis{
    Cl_Assertion Assert(bool Condition)
    {return Cl_AssertTrue.Create(Condition);}
}